//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaphaelFreiWeb.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RaphaelFreiWeb.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Home_DevRole {
            get {
                return ResourceManager.GetString("Home_DevRole", resourceCulture);
            }
        }
        
        public static string Home_DevDesc {
            get {
                return ResourceManager.GetString("Home_DevDesc", resourceCulture);
            }
        }
        
        public static string Home_DeployedProjects {
            get {
                return ResourceManager.GetString("Home_DeployedProjects", resourceCulture);
            }
        }
        
        public static string Home_AllProjectsBtn {
            get {
                return ResourceManager.GetString("Home_AllProjectsBtn", resourceCulture);
            }
        }
        
        public static string Projects_PageSubtitle {
            get {
                return ResourceManager.GetString("Projects_PageSubtitle", resourceCulture);
            }
        }
        
        public static string NotFound_ErrorTitle {
            get {
                return ResourceManager.GetString("NotFound_ErrorTitle", resourceCulture);
            }
        }
        
        public static string NotFound_ErrorDesc {
            get {
                return ResourceManager.GetString("NotFound_ErrorDesc", resourceCulture);
            }
        }
        
        public static string NotFound_HomeBtn {
            get {
                return ResourceManager.GetString("NotFound_HomeBtn", resourceCulture);
            }
        }
        
        public static string Nav_Projects {
            get {
                return ResourceManager.GetString("Nav_Projects", resourceCulture);
            }
        }
        
        public static string Nav_Resume {
            get {
                return ResourceManager.GetString("Nav_Resume", resourceCulture);
            }
        }
        
        public static string Projects_PageTitle {
            get {
                return ResourceManager.GetString("Projects_PageTitle", resourceCulture);
            }
        }
        
        public static string NotFound_PageTitle {
            get {
                return ResourceManager.GetString("NotFound_PageTitle", resourceCulture);
            }
        }
        
        public static string Home_PageTitle {
            get {
                return ResourceManager.GetString("Home_PageTitle", resourceCulture);
            }
        }
        
        public static string Date_InDevelopment {
            get {
                return ResourceManager.GetString("Date_InDevelopment", resourceCulture);
            }
        }
        
        public static string Date_Present {
            get {
                return ResourceManager.GetString("Date_Present", resourceCulture);
            }
        }
        
        public static string Resume_PageTitle {
            get {
                return ResourceManager.GetString("Resume_PageTitle", resourceCulture);
            }
        }
        
        public static string Resume_PageSubtitle {
            get {
                return ResourceManager.GetString("Resume_PageSubtitle", resourceCulture);
            }
        }
        
        public static string Resume_Experience {
            get {
                return ResourceManager.GetString("Resume_Experience", resourceCulture);
            }
        }
        
        public static string Resume_Education {
            get {
                return ResourceManager.GetString("Resume_Education", resourceCulture);
            }
        }
        
        public static string Resume_Skills {
            get {
                return ResourceManager.GetString("Resume_Skills", resourceCulture);
            }
        }
        
        public static string Time_Year {
            get {
                return ResourceManager.GetString("Time_Year", resourceCulture);
            }
        }
        
        public static string Time_Years {
            get {
                return ResourceManager.GetString("Time_Years", resourceCulture);
            }
        }
        
        public static string Time_Month {
            get {
                return ResourceManager.GetString("Time_Month", resourceCulture);
            }
        }
        
        public static string Time_Months {
            get {
                return ResourceManager.GetString("Time_Months", resourceCulture);
            }
        }
        
        public static string Time_LessOneMonth {
            get {
                return ResourceManager.GetString("Time_LessOneMonth", resourceCulture);
            }
        }
        
        public static string Cert_Verify {
            get {
                return ResourceManager.GetString("Cert_Verify", resourceCulture);
            }
        }
        
        public static string Resume_DownloadPDF {
            get {
                return ResourceManager.GetString("Resume_DownloadPDF", resourceCulture);
            }
        }
    }
}
